#! /bin/sh
#
# /usr/bin/gsmsmsspool: Queues SMS for sending
#
# written by Matthias Goebl <matthias.goebl@goebl.net>

SPOOLDIR=/var/spool/sms
PRIORITIES=3
test -r /etc/default/gsm-utils && . /etc/default/gsm-utils

if [ -z "$1" ]; then
  echo "Usage: gsmsmsspool NUMBER [MESSAGE]"
  exit 1
fi

# the default priority can be overridden by the environment variable GSMSMS_PRIORITY
priority=$PRIORITIES
test -n "$GSMSMS_PRIORITY" && priority="$GSMSMS_PRIORITY"
# the default reply email address can be overridden by the environment variable GSMSMS_NOTIFY
notify=`id -un`		# default notify
test -n "$GSMSMS_NOTIFY" && notify="$GSMSMS_NOTIFY"

tmpfile="$SPOOLDIR/tmp/`date +%s`.$$"
umask 022
echo "$1	$notify" > "$tmpfile"
if [ -n "$2" ]; then
  echo -n "$2" | head -c 160 >> "$tmpfile"
else
  head -c 160 >> "$tmpfile"
fi

if [ "`id -u`" = "0" ]; then
  chown gsmsms:gsmsms "$tmpfile"
fi

mv "$tmpfile" "$SPOOLDIR/queue$priority/"
